### ISSUE TITLE
[new feature] echo messages in the right part of the minibuffer

### ISSUE THREAD

**Issue by junyi-hou** [kiennq/emacs-mini-modeline#51]
I'll start by thanking you for this great package!

It would be great to have an option to echo messages in the right part (as oppose to the left part) of the minibuffer since traditionally the left part of the modeline has more important informations (e.g., evil state, whether the buffer is modified).

I think this is relatively easy to implement (correct me if I am wrong!): change
```
(setq mini-modeline--cache
      (mini-modeline--multi-lr-render
        (if mini-modeline--msg
           (format-mode-line '(:eval (mini-modeline-msg)))
         (format-mode-line mini-modeline-l-format))
	(format-mode-line mini-modeline-r-format)))
```
to
```
(setq mini-modeline--cache
      (mini-modeline--multi-lr-render
       (format-mode-line mini-modeline-l-format)
       (if mini-modeline--msg
           (format-mode-line '(:eval (mini-modeline-msg)))
         (format-mode-line mini-modeline-r-format))))
```
in `mini-modeline-display` should do the trick.

Let me know what you think and I can submit a PR.

**Comment by kiennq** [comment]
Yes, please submit a PR for that, I would prefer something configurable than just hardcode it to the left or right side

**Comment by junyi-hou** [comment]
For sure, I was also thinking add a `defcustom` option for that.

**Comment by devmsv** [comment]
solved by [https://github.com/kiennq/emacs-mini-modeline/pull/68](#68)
Can be close now

**Comment by QiangF** [comment]
Display on the right is not ergonomic. The start point is not fixed ,  user need first eye search the beginning, unless you are Arabian.

**Comment by devmsv** [comment]
I see 3 possibilities:

1. Don't do anything special and pad to the left
1. fix a point and cut messages on the right side
1. fix a point/maximum lenght and display messages in multiple lines
